config/routes.rb
Rails.application.routes.draw do

  resources :gossips do
    resources :comments
  end

  root "gossips#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :commenter, :text, presence: true

  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ActiveRecord::Base
	validates :celebrity_name, :title, :author, :date_published, :story, presence: true
	validates :gossip_scale, numericality: {in: [1,2,3,4,5,6,7,8,9,10]}

	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @gossip = Gossip.find(params[:gossip_id])
    @comment = @gossip.comments.create(comment_params)
    redirect_to gossip_path(@gossip)
  end

  def edit
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = comment.find(params[:id])

    if @comment.update(comment_params)
      redirect_to comment_path(@comment)
    else
      render 'edit'
    end
  end

  def destroy
    @gossip = Gossip.find(params[:gossip_id])
    @comment = @gossip.comments.find(params[:id])
    @comment.destroy

    redirect_to gossip_path(@gossip)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :text, :gossip_id)
    end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
	def index
		@gossips = Gossip.all
	end

	def show
		@gossip = Gossip.find(params[:id])
	end

	def new
		@gossip = Gossip.new
	end

	def create
		@gossip = Gossip.new(gossip_params)

		if @gossip.save
			redirect_to gossip_path(@gossip)
		else
			render 'new'
		end
	end

	def edit
		@gossip = Gossip.find(params[:id])
	end

	def update
		@gossip = Gossip.find(params[:id])

		if @gossip.update(gossip_params)
			redirect_to gossip_path(@gossip)
		else
			render 'edit'
		end
	end

	def destroy
		@gossip = Gossip.find(params[:id])
		@gossip.destroy

		redirect_to gossips_path
	end

private
	def gossip_params
		params.require(:gossip).permit(:celebrity_name, :title, :author, :date_published, :gossip_scale, :story)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div class="comments">
	<p>
	  <strong>Commenter:</strong>
	  <%= comment.commenter %>
	</p>
	 
	<p>
	  <strong>Text:</strong>
	  <%= comment.text %>
	</p>
</div>
<p>
  <%= link_to 'Destroy Comment', [comment.gossip, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@gossip, @gossip.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', gossip_path(@gossip) %>

app/views/gossips/_form.html.erb
<% if @gossip.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@gossip.errors.count, "error") %> prohibited
    this gossip from being saved:
  </h2>
  <ul>
    <% @gossip.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
  
<%= form_for @gossip do |f| %>
<p>
	<%= f.label :celebrity_name %><br>
	<%= f.text_field :celebrity_name %>
</p>
<p>
	<%= f.label :title %><br>
	<%= f.text_field :title %>
</p>
<p>
	<%= f.label :author %><br>
	<%= f.text_field :author %>
</p>
<p>
	<%= f.label :date_published %><br>
	<%= f.text_field :date_published %>
</p>
<p>
	<%= f.label :gossip_scale %><br>
	<%= f.select :gossip_scale, ['Select a rating',1, 2, 3, 4, 5, 6,7, 8, 9, 10]%>
</p>
<p>
	<%= f.label :story %><br>
	<%= f.text_field :story %>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>

app/views/gossips/edit.html.erb
<h1>Edit Dat Shit Yo</h1>

<%= render 'form' %>

<%= link_to 'Back', gossips_path %>

app/views/gossips/index.html.erb
<h1>OH NO SHE DIDN'T! Today's Hottest Celebrity Gossip</h1>

<%= link_to 'New gossip', new_gossip_path %>
<table>
  <tr>
    <th>Celebrity Name</th>
    <th>Title</th>
    <th>Author</th>
    <th>Date Published</th>
    <th>Gossip Scale </th>
  </tr>
 
  <% @gossips.each do |gossip| %>
    <tr>
      <td><%= gossip.celebrity_name %></td>
      <td><%= gossip.title %></td>
      <td><%= gossip.author %></td>
      <td><%= gossip.date_published%></td>
      <td><%= gossip.gossip_scale%></td>
      <td><%= link_to 'Show', gossip_path(gossip) %></td>
      <td><%= link_to 'Edit', edit_gossip_path(gossip) %></td>
      <td><%= link_to 'Destroy', gossip_path(gossip),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<img src="http://nyulocal.com/wp-content/uploads/2009/04/britney-spears-ugly-glasses-stoned.jpg">

app/views/gossips/new.html.erb
<h1>Add Some 411 Bitche$</h1>

<%= render 'form' %>

<%= link_to 'Back', gossips_path %>

app/views/gossips/show.html.erb
<h1>The Lowdown</h1>

<p><strong>Celebrity Name:</strong> <%= @gossip.celebrity_name %></p>

<p><strong>Title: </strong><%= @gossip.title %></p>

<p><strong>Author: </strong><%= @gossip.author %></p>

<p><strong>Date Published: </strong><%= @gossip.date_published %></p>

<p><strong>Gossip Scale: </strong><%= @gossip.gossip_scale %></p>

<p><strong>Story: </strong><%= @gossip.story %></p>

<hr><br>

<h2>Comments</h2>
<%= render @gossip.comments %>

<h2>Add Some Sass:</h2>

<%= render 'comments/form' %>

<p><%= link_to "Gossip List", gossips_path %></p>
 
<p><%= link_to "Edit", edit_gossip_path(@gossip) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OhNoSheDidnt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>
<div class="container">


<%= yield %>

</div>
</body>
</html>